### ISSUE TITLE
Add contribution documentation

### ISSUE THREAD

**Issue by corvus-ch** [appuio/component-openshift4-oauth#5]
* [x] [CHANGELOG.md](https://keepachangelog.com/en/1.0.0/)
* [x] [CONTRIBUTING.md](https://github.com/projectsyn/commodore/blob/master/CONTRIBUTING.md)
* [x] BSD-3 License
* [x] Bootstrap documentation
* [x] GitHub actions for testing
* [x] GitHub Issue/PR templates

**Comment by tobru** [comment]
`CONTRIBUTING.md` might not be needed, I'll check this.

**Comment by corvus-ch** [comment]
Some thoughts on the contribution guide. GitHub strongly suggests to add one. See https://github.com/appuio/component-openshift4-oauth/community. As we expect to have a plethora of components like this one, we would have maintain all those contribution guides and apply changes to all of them if we change something. This is not practical. Instead I suggest to have a contribution guide at https://syn.tools/ and just link to there.

**Comment by corvus-ch** [comment]
Bootsrapping the documentation was done based on the assumption, that it will be embedded into https://syn.tools.

**Comment by corvus-ch** [comment]
Implemented in #6.
